# PostgreSQL. Versions 9.1 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medic_book_development

test:
  <<: *default
  database: medic_book_test

production:
  <<: *default
  database: medic_book_production
  username: medic-book
  password: <%= ENV['MEDIC_BOOK_DATABASE_PASSWORD'] %>
